# Generated by Django 5.0.6 on 2024-07-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_share'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Share',
        ),
    ]
